### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by LifeIsStrange** [zero-one-group/ionic-react-native-flutter#7]
Any conclusions on the comparative developer experience, code quality/clarity and runtime performance?
@rohmad-st

**Comment by rubiagatra** [comment]
You can check our conclusion here https://medium.com/@zeroonegroup/ionic-react-native-and-flutter-in-one-nx-monorepo-ff58196a0125 for DX and Code style.

For run time performance we are not benchmarking yet.

**Comment by LifeIsStrange** [comment]
You might find https://ionicframework.com/blog/ionic-vs-react-native-performance-comparison/
Interesting
It shows evidence against the myth that of other frameworks being more performant and energy efficient.
Flutter has a lot of stutter/jank and I bet it is generally less performant than Ionic too.
